#pragma once

#include <stddef.h>
#include <stdint.h>

// Generated by tools/prepare_model.py from Arduino-ESP32 3.3.12's ESP-SR 2.5.3 bundle.
// Verify these bytes before passing the model partition to esp_srmodel_init().
namespace weather_speech_model {
constexpr size_t kImageBytes = 3340296u;
constexpr char kModelName[] = "mn7_en";
constexpr char kSha256Hex[] = "c7ea01954baaa1fa89ef6b88ba8819edcbf419b7aba1e093950f8badf1a6c328";
constexpr uint8_t kSha256[32] = {
    0xc7, 0xea, 0x01, 0x95, 0x4b, 0xaa, 0xa1, 0xfa,
    0x89, 0xef, 0x6b, 0x88, 0xba, 0x88, 0x19, 0xed,
    0xcb, 0xf4, 0x19, 0xb7, 0xab, 0xa1, 0xe0, 0x93,
    0x95, 0x0f, 0x8b, 0xad, 0xf1, 0xa6, 0xc3, 0x28,
};
}  // namespace weather_speech_model
