#pragma once

#include <stddef.h>
#include <stdint.h>

// Flash-resident, 16 kHz signed 16-bit mono PCM. No cloud request or runtime synthesis.
enum class SpeechClip : uint16_t {
  N0,
  N1,
  N2,
  N3,
  N4,
  N5,
  N6,
  N7,
  N8,
  N9,
  N10,
  N11,
  N12,
  N13,
  N14,
  N15,
  N16,
  N17,
  N18,
  N19,
  N20,
  N30,
  N40,
  N50,
  N60,
  N70,
  N80,
  N90,
  Hundred,
  Thousand,
  Minus,
  Point,
  CurrentPM25,
  Micrograms,
  OutdoorTemperature,
  DegreesCelsius,
  Humidity,
  Percent,
  HeatIndex,
  ForecastWind,
  KilometresPerHour,
  RainNextHour,
  Unavailable,
  CurrentDataOld,
  ForecastUnavailable,
  ForecastOld,
  IndoorTemperature,
  IndoorHumidity,
  OutdoorHumidity,
  RainInterval,
  Until,
  AM,
  PM,
  Oh,
  Sunday,
  Monday,
  Tuesday,
  Wednesday,
  Thursday,
  Friday,
  Saturday,
  PMForecast,
  Window,
  RainChance,
  FeelsLike,
  Wind,
  Gust,
  Morning,
  Afternoon,
  RainAmount,
  Millimetres,
  HistoryWindow,
  LatestPM,
  AveragePM,
  LowestPM,
  HighestPM,
  LatestTemperature,
  LatestHeatIndex,
  BatteryVoltage,
  Volts,
  ApproximateBattery,
  UnavailableValue,
  Old,
  Observed,
  Near90Forecast,
  RainInAnHour,
  PMForecastRange,
  ChanceBelow70Is,
  Lowest,
  Highest,
  Battery,
  PercentCapacity,
  TodayMorning,
  TomorrowMorning,
  TodayAfternoon,
  TomorrowAfternoon,
  LowerForecastPMThan,
  SimilarPM,
  ComparisonUnavailable,
  Warning,
  HighRainChance,
  RideRainWarning,
  NoChangeOnArrival,
  FallOnArrival,
  RiseOnArrival,
  ArrivalOutcomeUncertain,
  ObservedFastRise,
  ObservedFastRebound,
  ObservedReboundStarting,
  ObservedRecentMedians35,
  ObservedMoistCoolingClearing,
  ObservedDryClearing,
  ObservedReductionForming,
  ObservedRapidReduction,
  LatestSensorReading,
  ObservedStatusUnavailable,
  DemoData,
  Count
};

struct SpeechClipData {
  const int16_t *samples;
  size_t count;
};

SpeechClipData speechClipData(SpeechClip clip);
