"""Frozen round-two nonlinear PM2.5 event-direction candidate.

The first candidate improved large falling-transition errors but worsened each
near-term validation day's MAE. The clarified round-two objective emphasizes
anticipation of rises/falls, so this revision classifies event direction and uses
a robust within-event magnitude. It does not optimize mean absolute error or
produce a small correction solely to appear nonflat. All parameters were declared
before any fit or outcome scoring of this revision.

The caller supplies only training outcomes fully completed before the issue,
including the final 15-minute bucket. No internal validation, adaptive weights,
date-specific branches, file access, network access, or persistent fitted state
is used. September 20 was already known when this revision was designed, so later
scores on this snapshot are exploratory rather than a new untouched holdout.
"""

from __future__ import annotations

from collections.abc import Mapping

import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingClassifier
from threadpoolctl import threadpool_limits


MODEL_NAME = "sep21_nonlinear_r2_direction40"
MIN_TRAINING_ROWS = 120
TRAINING_LOOKBACK_SECONDS = 14 * 86400
EVENT_CHANGE_THRESHOLD = 10.0
FEATURES = (
    "fresh", "closedLevel", "freshOffset", "delta15", "delta30", "delta60",
    "delta120", "sd60", "mean3Offset", "temp", "rh", "tempDelta30",
    "rhDelta30", "sinTarget", "cosTarget", "camsCurrent", "camsTarget",
    "camsDelta", "priorRainMm", "duringRainMm", "priorRainProbMean",
    "duringRainProbMean", "firstWetLeadHours", "hoursUntilExpectedWetEnd",
    "wetTempMinDeltaC", "targetTempDeltaC", "targetRhDeltaPct",
    "targetWind10DeltaKmh", "targetWind925MeanKmh", "targetLeadHours",
    "targetDurationHours",
)
PARAMETERS = {
    "loss": "log_loss",
    "learning_rate": 0.05,
    "max_iter": 40,
    "max_depth": 2,
    "max_leaf_nodes": 4,
    "min_samples_leaf": 24,
    "l2_regularization": 20.0,
    "max_bins": 32,
    "class_weight": "balanced",
    "early_stopping": False,
    "random_state": 1729,
}


def _query_series(query: pd.Series | pd.DataFrame | Mapping) -> pd.Series:
    if isinstance(query, pd.DataFrame):
        if len(query) != 1:
            raise ValueError("query must contain exactly one row")
        return query.iloc[0]
    return query if isinstance(query, pd.Series) else pd.Series(query)


def _numeric_features(frame: pd.DataFrame) -> np.ndarray:
    values = frame.reindex(columns=FEATURES).apply(
        pd.to_numeric, errors="coerce"
    ).to_numpy(dtype=float)
    values[~np.isfinite(values)] = np.nan
    return values


def _impute_from_training(
    training: np.ndarray, query: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    train_missing, query_missing = np.isnan(training), np.isnan(query)
    medians = np.zeros(training.shape[1], dtype=float)
    for column in range(training.shape[1]):
        observed = training[~train_missing[:, column], column]
        if len(observed):
            medians[column] = float(np.median(observed))
    return (
        np.column_stack((np.where(train_missing, medians, training),
                         train_missing.astype(float))),
        np.column_stack((np.where(query_missing, medians, query),
                         query_missing.astype(float))),
    )


def predict_details(
    train_x: pd.DataFrame,
    train_y: np.ndarray | pd.Series,
    query: pd.Series | pd.DataFrame | Mapping,
    train_issues: np.ndarray | pd.Series,
    issue: float,
    target_kind: str,
    *,
    _raise_fit_errors: bool = False,
) -> dict:
    """Forecast absolute PM2.5 from a learned rise/fall/stable event class.

    Input row order is positional across training features, labels, and epoch
    issue times. The identical fixed estimator is used for every target kind.
    The caller gates full target completion; this function additionally enforces
    the preceding 14 days and excludes issue times at/after the current issue.
    Optional missing predictors are imputed from training only and marked.
    A rise/fall is a completed-label change of at least +/-10 micrograms/m3.
    Class-balanced fitting emphasizes minority directions. A maximum-probability
    stable class or tied decision returns fresh; a rise/fall adds the median
    observed training change within that predicted class. Under 120 eligible
    examples, or fewer than two observed classes, uses fresh. Absent query
    fresh gives prediction=None (the float compatibility API returns NaN).
    Diagnostics are generated by the same fit, with no new confidence gate.
    """
    query_values = _numeric_features(pd.DataFrame([_query_series(query)]))
    fresh = float(query_values[0, 0])
    result = {
        "schemaVersion": 1,
        "prediction": max(0.0, fresh) if np.isfinite(fresh) else None,
        "predictedClass": None,
        "decisionReason": None,
        "fallbackReason": None,
        "classScores": {},
        "scoreInterpretation": "Uncalibrated class-balanced classifier scores; not event probabilities",
        "trainingClassCounts": {},
        "classMedianChanges": {},
        "trainingCount": 0,
        "magnitudeMethod": "fresh_reference",
    }

    def fallback(reason):
        result["decisionReason"] = result["fallbackReason"] = reason
        return result

    if not np.isfinite(fresh):
        return fallback("required_fresh_reference_unavailable")
    if not np.isfinite(issue):
        return fallback("invalid_issue")
    labels = np.asarray(train_y, dtype=float).reshape(-1)
    issues = np.asarray(train_issues, dtype=float).reshape(-1)
    if len(train_x) != len(labels) or len(train_x) != len(issues):
        raise ValueError("train_x, train_y, and train_issues must have equal length")
    if len(labels) < MIN_TRAINING_ROWS:
        return fallback("insufficient_input_rows")
    values = _numeric_features(train_x)
    valid = (
        np.isfinite(labels)
        & np.isfinite(values[:, 0])
        & np.isfinite(issues)
        & (issues >= float(issue) - TRAINING_LOOKBACK_SECONDS)
        & (issues < float(issue))
    )
    result["trainingCount"] = int(valid.sum())
    if result["trainingCount"] < MIN_TRAINING_ROWS:
        return fallback("insufficient_eligible_rows")
    values = values[valid]
    changes = labels[valid] - values[:, 0]
    directions = np.where(changes >= EVENT_CHANGE_THRESHOLD, 1,
                          np.where(changes <= -EVENT_CHANGE_THRESHOLD, -1, 0))
    result["trainingClassCounts"] = {
        str(c): int(np.sum(directions == c)) for c in (-1, 0, 1)
    }
    result["classMedianChanges"] = {
        str(c): float(np.median(changes[directions == c]))
        if np.any(directions == c) else None for c in (-1, 0, 1)
    }
    if len(np.unique(directions)) < 2:
        return fallback("insufficient_classes")
    train_ready, query_ready = _impute_from_training(values, query_values)
    try:
        with threadpool_limits(limits=1):
            model = HistGradientBoostingClassifier(**PARAMETERS)
            model.fit(train_ready, directions)
            probabilities = model.predict_proba(query_ready)[0]
    except Exception as error:
        if _raise_fit_errors:
            raise
        result["prediction"] = None
        result["errorType"] = type(error).__name__
        return fallback("fit_or_prediction_failure")
    if not np.isfinite(probabilities).all():
        return fallback("nonfinite_class_scores")
    result["classScores"] = {
        str(int(c)): float(p) for c, p in zip(model.classes_, probabilities)
    }
    winners = np.flatnonzero(np.isclose(probabilities, probabilities.max(),
                                      rtol=0.0, atol=1e-12))
    if len(winners) != 1:
        return fallback("tied_class_scores")
    direction = int(model.classes_[winners[0]])
    result["predictedClass"] = direction
    if direction == 0:
        result["decisionReason"] = "steady_class"
        return result
    change = float(np.median(changes[directions == direction]))
    result.update(prediction=max(0.0, fresh + change),
                  decisionReason="event_class", magnitudeMethod="within_class_median_change")
    return result


def predict(train_x, train_y, query, train_issues, issue, target_kind) -> float:
    """Compatibility interface; diagnostics and point use the same single fit."""
    result = predict_details(train_x, train_y, query, train_issues, issue,
                             target_kind, _raise_fit_errors=True)
    return float(result["prediction"]) if result["prediction"] is not None else float("nan")
