#!/usr/bin/env python3
"""Restore and verify the exact ESP-SR model bundle used by this sketch.

This copies Espressif's binary without modifying or retraining its models.
No ESP-IDF project, ESP-SR checkout, or third-party Python module is needed.
"""

import argparse
import hashlib
import json
from pathlib import Path
import struct
import tempfile
import urllib.request
import zipfile

PROJECT_DIR = Path(__file__).resolve().parent.parent
CORE_VERSION = "3.3.12"
IDF_VERSION = "5.5.5"
ESP_SR_VERSION = "2.5.3"
SDK_VERSION = "idf-release_v5.5-b774170f-v3"
ARCHIVE_URL = (
    "https://github.com/espressif/arduino-esp32/releases/download/3.3.12/"
    "esp32s3-libs-3.3.12.zip"
)
ARCHIVE_SHA256 = "08f4e7292fee97dc011dc64e3c670a9a4e83a6b52a604c4b9b18ab2885cdd092"
MODEL_SHA256 = "c7ea01954baaa1fa89ef6b88ba8819edcbf419b7aba1e093950f8badf1a6c328"
MODEL_BYTES = 3340296
MODEL_OFFSET = 0x810000
MODEL_PARTITION_BYTES = 0x7F0000
MODEL_MEMBER = "esp32s3-libs/esp_sr/srmodels.bin"
EXPECTED_MODELS = {"vadnet1_medium", "mn7_en", "fst", "wn9_hiesp"}


def verify_model_image(data):
    """Check the pinned hash and inspect ESP-SR's packed model directory.

    Format references: esp-sr/model/pack_model.py and src/model_path.c.
    Return JSON-compatible metadata, without copying model weights into JSON.
    """
    digest = hashlib.sha256(data).hexdigest()
    if len(data) != MODEL_BYTES or digest != MODEL_SHA256:
        raise ValueError(
            "Model image does not match Arduino-ESP32 3.3.12's ESP-SR bundle. "
            f"Expected {MODEL_BYTES} bytes / SHA-256 {MODEL_SHA256}; "
            f"got {len(data)} bytes / {digest}."
        )

    count = struct.unpack_from("<I", data)[0]
    if count != len(EXPECTED_MODELS):
        raise ValueError("Unexpected number of packed models")
    cursor = 4
    result = []
    payload_ranges = []

    def read_name():
        nonlocal cursor
        if cursor + 32 > len(data):
            raise ValueError("Truncated model directory")
        name = data[cursor:cursor + 32].split(b"\0", 1)[0].decode("ascii")
        cursor += 32
        if not name or "/" in name or "\\" in name:
            raise ValueError("Invalid packed model/file name")
        return name

    for _ in range(count):
        name = read_name()
        file_count = struct.unpack_from("<I", data, cursor)[0]
        cursor += 4
        if not 1 <= file_count <= 16:
            raise ValueError("Invalid packed model file count")
        files = []
        model_info = None
        for _ in range(file_count):
            filename = read_name()
            offset, size = struct.unpack_from("<II", data, cursor)
            cursor += 8
            if size == 0 or offset + size > len(data):
                raise ValueError("Packed model payload is out of bounds")
            payload_ranges.append((offset, offset + size))
            files.append({"name": filename, "offset": offset, "bytes": size})
            if filename == "_MODEL_INFO_":
                model_info = data[offset:offset + size].decode("ascii").strip()
        result.append({"name": name, "info": model_info, "files": files})

    if {item["name"] for item in result} != EXPECTED_MODELS:
        raise ValueError("Expected English MultiNet 7 bundle is missing")
    previous_end = cursor
    for start, end in sorted(payload_ranges):
        if start < previous_end:
            raise ValueError("Packed model payload overlaps another entry")
        previous_end = end
    return result


def read_archive(path):
    path = Path(path)
    with path.open("rb") as source:
        digest = hashlib.file_digest(source, "sha256").hexdigest() if hasattr(hashlib, "file_digest") else None
    if digest is None:
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
    if digest != ARCHIVE_SHA256:
        raise ValueError("SDK archive checksum does not match the pinned Espressif release")
    with zipfile.ZipFile(path) as archive:
        if archive.getinfo(MODEL_MEMBER).file_size != MODEL_BYTES:
            raise ValueError("Unexpected model member size in SDK archive")
        return archive.read(MODEL_MEMBER)


def generated_header():
    digest = bytes.fromhex(MODEL_SHA256)
    rows = [
        "    " + ", ".join(f"0x{b:02x}" for b in digest[i:i + 8]) + ","
        for i in range(0, len(digest), 8)
    ]
    return (
        "#pragma once\n\n#include <stddef.h>\n#include <stdint.h>\n\n"
        "// Generated by tools/prepare_model.py from Arduino-ESP32 3.3.12's ESP-SR 2.5.3 bundle.\n"
        "// Verify these bytes before passing the model partition to esp_srmodel_init().\n"
        "namespace weather_speech_model {\n"
        f"constexpr size_t kImageBytes = {MODEL_BYTES}u;\n"
        'constexpr char kModelName[] = "mn7_en";\n'
        f'constexpr char kSha256Hex[] = "{MODEL_SHA256}";\n'
        "constexpr uint8_t kSha256[32] = {\n" + "\n".join(rows) + "\n};\n"
        "}  // namespace weather_speech_model\n"
    )


def write_assets(data):
    models = verify_model_image(data)
    target = PROJECT_DIR / "flash"
    target.mkdir(parents=True, exist_ok=True)
    (target / "model.bin").write_bytes(data)
    manifest = {
        "file": "model.bin",
        "bytes": MODEL_BYTES,
        "sha256": MODEL_SHA256,
        "arduino_esp32_version": CORE_VERSION,
        "esp_idf_version": IDF_VERSION,
        "esp_sr_version": ESP_SR_VERSION,
        "arduino_sdk_package": SDK_VERSION,
        "upstream_archive_url": ARCHIVE_URL,
        "upstream_archive_sha256": ARCHIVE_SHA256,
        "upstream_archive_member": MODEL_MEMBER,
        "partition_label": "model",
        "partition_type": "data",
        "partition_subtype": "spiffs",
        "partition_offset": "0x810000",
        "partition_bytes": MODEL_PARTITION_BYTES,
        "runtime_command_model": "mn7_en",
        "model_bytes_modified": False,
        "runtime_wakenet_enabled": False,
        "note": (
            "This is the original complete Espressif bundle. wn9_hiesp data remains in flash, "
            "but the dashboard disables WakeNet before creating AFE and does not instantiate it. "
            "The spiffs subtype labels a raw ESP-SR container; do not format or mount it as SPIFFS."
        ),
        "license_file": "../../LICENSES/ESP-SR-ESPRESSIF-MIT.txt",
        "license_source": "https://github.com/espressif/esp-sr/blob/0a6e15d5ea9c7f5402093439f3af4c9250ae0d8d/LICENSE",
        "license_git_blob_sha": "8e206f3bc38f5fa84a4956f2d5030ca17daea0d7",
        "models": models,
    }
    (target / "model_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (PROJECT_DIR / "SpeechModelInfo.h").write_text(generated_header(), encoding="utf-8")
    print(f"Verified model: {MODEL_BYTES:,} bytes, SHA-256 {MODEL_SHA256}")
    print(f"Wrote {target / 'model.bin'}")
    print("Wrote model_manifest.json and SpeechModelInfo.h")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--sdk-dir", type=Path, help="ESP32-S3 SDK folder containing esp_sr/srmodels.bin")
    source.add_argument("--archive", type=Path, help="Official esp32s3-libs-3.3.12.zip")
    source.add_argument("--download", action="store_true", help="Download the pinned official 92 MB SDK archive")
    args = parser.parse_args()
    try:
        if args.sdk_dir:
            versions = (args.sdk_dir / "versions.txt").read_text(encoding="utf-8")
            if "espressif__esp-sr: 2.5.3" not in versions:
                raise ValueError("The supplied SDK is not the expected ESP-SR 2.5.3 SDK")
            data = (args.sdk_dir / "esp_sr" / "srmodels.bin").read_bytes()
        elif args.archive:
            data = read_archive(args.archive)
        elif args.download:
            print(f"Downloading {ARCHIVE_URL}")
            with tempfile.TemporaryDirectory(prefix="weather-speech-model-") as temporary:
                archive_path = Path(temporary) / "esp32s3-libs-3.3.12.zip"
                with urllib.request.urlopen(ARCHIVE_URL, timeout=60) as response, archive_path.open("wb") as output:
                    while True:
                        chunk = response.read(1024 * 1024)
                        if not chunk:
                            break
                        output.write(chunk)
                data = read_archive(archive_path)
        else:
            data = (PROJECT_DIR / "flash" / "model.bin").read_bytes()
        write_assets(data)
    except (OSError, ValueError, KeyError, struct.error, zipfile.BadZipFile) as error:
        parser.exit(1, f"Model preparation failed: {error}\n")


if __name__ == "__main__":
    main()
